repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args:
        - --line-length 120
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
        -   --profile
        -   black
        -   --filter-files
        -   --gitignore
        -   -skip-gitignore
-   repo: https://github.com/pycqa/pylint
    rev: v2.15.8
    hooks:
      - id: pylint
        args:
        -   --disable=missing-docstring,invalid-name,line-too-long,
                      fixme,wrong-import-position,import-error,duplicate-code, logging-fstring-interpolation
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.0'
    hooks:
    -   id: mypy
